### ISSUE TITLE
Drag & Drop functionality on touch screen devices

### ISSUE THREAD

**Issue by lPieter** [BogdanMihaiciuc/BMCollectionView#38]
Hi, I enabled the Drag & Drop funcionality on the collection view (also set move, transfer etc.) and on PC it works perfectly. But when I tried it on touch device (touch TV or tablet) it give me an error:   
"Uncaught TypeError: Cannot read property 'length' of undefined at BMCollectionViewWidget.collectionViewCellWasLongClicked ...."
![collectionDragDropIssue](https://user-images.githubusercontent.com/72861655/128344620-4d4bacba-cc81-4342-9ad9-3b631709903a.png)

this error occurs every time when I try to drag & drop item in collection.

My ThingWorx version is 9.0.1-b103 and currently I'm using BMCoreUIWidgets-min-2.6.3 (in never version doesn't work the "Configure" button). I also tried it at newer ThingWorx version (9.1.0-b10877) and with newer version of BMCoreUIWidgets (up to version 2.6.8) but the result are always the same.

Do you have any suggestions or work-arounds?

Thank you for answer.
Lubos

**Comment by BogdanMihaiciuc** [comment]
Which OS/Browser are you using?

For touch devices I only tested on Safari for iOS and just assumed it works everywhere else too, so it's likely if you are using something else that I just didn't test for that platform and it's something I'll need to fix.

**Comment by lPieter** [comment]
Tablet (Lenovo):
OS: Android 10
Browser: Chrome 92.0.4515.131

Touch TV (samsung flip 2 wm85r):
OS: Tizen 5.0 : Samsung Proprietary OS (VDLinux)
Browser: Chrome (portable)

**Comment by BogdanMihaiciuc** [comment]
Thanks, I'll look into it

**Comment by BogdanMihaiciuc** [comment]
As a temporary workaround, you should be able to get it to work by setting a value for the **`CellSlideMenu`** property and setting the **`CellSlideMenuUseBuiltin`** property to `false`.

I will publish an update to resolve this soon.

**Comment by lPieter** [comment]
Hi Bogdan, thank you very much! It's now generating lots of errors (chrome issue) but on tablet the drag & drop functionality works good.
![collectionDragDropIntervention](https://user-images.githubusercontent.com/72861655/128504999-23cb56ff-b767-4b08-ac6e-9a6b51df4c5e.png)

I'll be looking forward for your update and thanks for the work with the collection.

**Comment by BogdanMihaiciuc** [comment]
This, and the `preventDefault` console messages should be fixed in release 2.6.9 (both Core UI and Collection View).

Please reopen this issue if you still have this problem.
