### ISSUE TITLE
The layout table type does not exist

### ISSUE THREAD

**Issue by aumasson** [BogdanMihaiciuc/BMCollectionView#57]
Hi,

As you can see in the screenshots, the layout type table does not exist.
I am in Thingworx 9.0.8.

The layout type is explained in the repository notes, but I can't find a way to set the BMCollection to a table type.
Is this not implemented yet? Is there any other way to do this?

![image](https://user-images.githubusercontent.com/102983762/182646286-50e39d73-b533-456f-970e-f1d102215dcd.png)
![image](https://user-images.githubusercontent.com/102983762/182646519-9ba2597d-c409-4331-91f6-8624d12f3c6f.png)
![image](https://user-images.githubusercontent.com/102983762/182646608-d895b351-a7e8-4a20-ac9b-9b4aa3a390ef.png)

**Comment by BogdanMihaiciuc** [comment]
Hello,

The table layout was deprecated a while back and can no longer be selected for newly created collection views.

You can obtain a similar layout, with more options than table had, by using flow layout, setting the max cells per row to 1 and using the expand flow setting.

**Comment by aumasson** [comment]
Hi,

I succeeded in obtaining the similar visual with your indications. Thank you !
