### ISSUE TITLE
Input text fields does not work with 9.3.4

### ISSUE THREAD

**Issue by hetenyer** [BogdanMihaiciuc/BMCollectionView#62]
Hell Bogdan,

I just wanted to report that we have upgraded to 9.3.4 TWX and the collection is no longer working on IOS devices for input fields. 
Cell selection and rendering the collection works just fine.  I've tried it with the recent version of the collection.

Thanks
Erik

**Comment by BogdanMihaiciuc** [comment]
Hello,

Are using the latest collection view/core ui release, 2.9? Also I assume the iOS device is also running the latest os release.

If so, could you send me a sample mashup where this issue can be reproduced so that I can test and resolve this?

**Comment by hetenyer** [comment]
Hello Bogdan, yes I was trying to use the 2.9 version of the collection.

Unfortunately I had to temporarily remove the extension so development can continue, but basically what it seemed to be the issue was the passive event listeners. On touch event the cell selection itself worked but to enter inputs into text fields or select anything in a dropdown was not. 

There was an older issue here that explained how to put a customClass in, so that made the collection cell selection and the input fields working pre 9.3.4, but I assume PTC had changed something because it works way differently now on mobile devices :)

I hope it helps

**Comment by BogdanMihaiciuc** [comment]
Alright, I will look into it.

**Comment by BogdanMihaiciuc** [comment]
You should be able to get these working by adding the `BMCollectionViewCellEventHandler` class to the `CustomClass` field on the text fields.

**Comment by hetenyer** [comment]
I think it might have been caused by some leftover extensions previously installed, we're going to cleanup and try again.

**Comment by hetenyer** [comment]
We tested the above solution and we are still unable to enter anything into out of the box input fields like text or dropdown. Reproducible on both android and ios.

**Comment by BogdanMihaiciuc** [comment]
Could you send me a sample mashup where this issue can be reproduced? I was not able to reproduce this using Thingworx 9.3.4 on the latest iOS with the custom class added to the text field.

Thanks!

**Comment by BogdanMihaiciuc** [comment]
Are you using pinned headers, pinned footers or scrollbar styles by any chance? I am able to reproduce this when either of those are enabled, but with those disabled, on iOS at least, it works even through a contained mashup.

**Comment by BogdanMihaiciuc** [comment]
You should be able to get this working by updating to [Core UI 2.9.1](https://github.com/BogdanMihaiciuc/BMCoreUI/releases/tag/2.9.1) or [Core UI Widgets 2.9.1](https://github.com/ptc-iot-sharing/BMCoreUIWidgets/releases/tag/2.9.1).

Note that you will still need to add the `BMCollectionViewCellEventHandler` custom class to your text field widgets.

If that release doesn't solve your issue, please reopen.

**Comment by hetenyer** [comment]
Hello Bogdan, Sorry for not coming back on this earlier. We managed to get it fixed, thank you for your help!
